// <auto-generated />
namespace FLASHBACKS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class section5Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(section5Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202210261523483_section5Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
