// <auto-generated />
namespace FLASHBACKS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class week7Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(week7Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202210222304582_week7Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
